### ISSUE TITLE
Amazon SNS

### ISSUE THREAD

**Issue by ForSite** [titansys/zender-gateways#10]
In terms of prices for sending SMS, I believe that there are no better values, since the free plan includes 1 million calls. I just don't know if SNS supports 2way.
In my country, Brazil. The sending gateways that the system has are charged in dollars in most of them, which makes it unusable.

[Amazon SNS](https://aws.amazon.com/pt/sns/)

[API](https://docs.aws.amazon.com/sns/latest/api/welcome.html)

**Comment by noriellecruz** [comment]
Customer has refunded. Development has been discarded.
