### ISSUE TITLE
Implement Zettatel SMS, Africa

### ISSUE THREAD

**Issue by compgeniuses** [titansys/zender-gateways#3]
https://www.zettatel.com/bulk-sms/

here is Sample SMS API Code.

```
<?php
$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => "https://sendsms.domain.tld/SMSApi/send",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "userid=user&password=PWD&mobile=91xxxxxxxxxx&msg=Hello+World%21+This+is+a+test+message%21&senderid=SENDER&msgType=text&duplicatecheck=true&output=json&sendMethod=quick",
  CURLOPT_HTTPHEADER => array(
    "apikey: somerandomuniquekey",
    "cache-control: no-cache",
    "content-type: application/x-www-form-urlencoded"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

Hope that Helps; if you need account for testing, ask.

**Comment by compgeniuses** [comment]
this supports custom sms endpoint

**Comment by snawaze** [comment]
function gatewaySend($phone, $message, &$system)
{
	/**
	 * Implement sending here
	 * @return bool:true
	 * @return bool:false
	 */

	
	$url = "https://sendsms.domain.tld/SMSApi/send";

	$curl = curl_init();
	
	$user_id = ""; //Your User ID Here
	$pass = "";		//Your User Password Here
	$sender_id = ""; //Sender ID
	$type = "";		//Type
	$dupc = ""; //Duplicate Check value here
	$output = ""; // Output
	$smethod = "";  // Send method

	curl_setopt_array($curl, array(
		CURLOPT_URL => $url,
		CURLOPT_RETURNTRANSFER => true,
		CURLOPT_ENCODING => '',
		CURLOPT_MAXREDIRS => 10,
		CURLOPT_TIMEOUT => 0,
		CURLOPT_FOLLOWLOCATION => true,
		CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
		CURLOPT_CUSTOMREQUEST => 'POST',
		CURLOPT_POSTFIELDS => array('userid' => $user_id, 'password' => $pass, 'mobile' => $phone, 'msg' => $message, 'sender_id' => $sender_id, 'type' => $type, 'duplicatecheck' => $dupc, 'output' => $output, 'sendMethod' => $smethod),
		CURLOPT_HTTPHEADER => array(),
	));

	$response = curl_exec($curl);
	curl_close($curl);
	return $response;
}

**Comment by noriellecruz** [comment]
> function gatewaySend($phone, $message, &$system) { /** * Implement sending here * @return bool:true * @return bool:false */
> 
> ```
> $url = "https://sendsms.domain.tld/SMSApi/send";
> 
> $curl = curl_init();
> 
> $user_id = ""; //Your User ID Here
> $pass = "";		//Your User Password Here
> $sender_id = ""; //Sender ID
> $type = "";		//Type
> $dupc = ""; //Duplicate Check value here
> $output = ""; // Output
> $smethod = "";  // Send method
> 
> curl_setopt_array($curl, array(
> 	CURLOPT_URL => $url,
> 	CURLOPT_RETURNTRANSFER => true,
> 	CURLOPT_ENCODING => '',
> 	CURLOPT_MAXREDIRS => 10,
> 	CURLOPT_TIMEOUT => 0,
> 	CURLOPT_FOLLOWLOCATION => true,
> 	CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
> 	CURLOPT_CUSTOMREQUEST => 'POST',
> 	CURLOPT_POSTFIELDS => array('userid' => $user_id, 'password' => $pass, 'mobile' => $phone, 'msg' => $message, 'sender_id' => $sender_id, 'type' => $type, 'duplicatecheck' => $dupc, 'output' => $output, 'sendMethod' => $smethod),
> 	CURLOPT_HTTPHEADER => array(),
> ));
> 
> $response = curl_exec($curl);
> curl_close($curl);
> return $response;
> ```
> 
> }

Hello @snawaze thanks for this but this will likely produce an error because you are directly returning the response. We will push a working controller in a few moments.

**Comment by noriellecruz** [comment]
@compgeniuses can you send us a detailed documentation of their API?

**Comment by compgeniuses** [comment]
find postman collections here:

[zettatel Postman_SMS_1667198978.zip](https://github.com/titansys/zender-gateways/files/9898697/zettatel.Postman_SMS_1667198978.zip)

**Comment by noriellecruz** [comment]
> find postman collections here:
> 
> [zettatel Postman_SMS_1667198978.zip](https://github.com/titansys/zender-gateways/files/9898697/zettatel.Postman_SMS_1667198978.zip)

After checking, the documentation is not clear. There are no response examples which will make it harder for our team to create a stable controller. We will close this issue for now until we find a complete documentation of their API.
