### ISSUE TITLE
Twilio sms problem

### ISSUE THREAD

**Issue by Gercekefsane** [titansys/zender-gateways#4]
Hello,
Messages allready sent but system showing Status: Queued

How can i fix it?

https://prnt.sc/8rLbDBOoIW5w

**Comment by noriellecruz** [comment]
Hi, did you added the callback ID properly in the gateway controller?

**Comment by noriellecruz** [comment]
This has been fixed in the upcoming update, the new twilio gateway controller doesn't need callback function enabled.
