### ISSUE TITLE
Implement Ultimate sms as a gateway for sending messages

### ISSUE THREAD

**Issue by compgeniuses** [titansys/zender-gateways#5]
Implement this. as an sms module
https://codecanyon.net/item/ultimate-sms-bulk-sms-application-for-marketing/20062631

**Comment by noriellecruz** [comment]
This was already created in the upcoming update. Unfortunately, our request for a custom sending gateway in the parameters of their API was not fulfilled by the author of that script. 

In that case, to use multiple sending gateways in their script, one has to create a client account for each gateway server and add the apitoken in the gateway controller to be added on the zender's side.

**Comment by compgeniuses** [comment]
thanks for the implementaton, it will surely still help alot of people as it is.
