### ISSUE TITLE
Telnyx Gateway Need.

### ISSUE THREAD

**Issue by iamdoulat** [titansys/zender-gateways#6]
Telnyx Gateway code: Kindly help me to create Telnyx gateway same as Twillio.

https://developers.telnyx.com/docs/api/v2/overview?lang=php

https://developers.telnyx.com/docs/v2/messaging/quickstarts/portal-setup

https://developers.telnyx.com/docs/v2

**Comment by noriellecruz** [comment]
This gateway has been added
